spring:
  profiles.active: default

---
spring:
    profiles: default

server:
    port: 7070

spring.datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exchange_rates?autoReconnect=true
    username: root
    password: purpose
    validation-query: SELECT 1
    test-on-borrow: true

spring.jpa:
  hibernate:
    ddlAuto: update
    naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
    show-sql: false
  database-platform: org.hibernate.dialect.MySQL5Dialect
  show-sql: false
#  properties:
#    jadira:
#      usertype:
#        autoRegisterUserTypes: true

spring.jmx:
  enabled: false

hibernate:
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect

spring.jackson.serialization:
  WRITE_DATES_AS_TIMESTAMPS: false

---
spring:
    profiles: production

server:
    port: 7070