server:
  port: 5000

spring.datasource:
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:exchange_rates;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
  username: sa
  password:

spring.h2.console:
  enabled: false
  path: /h2

spring.jpa:
  hibernate:
    ddlAuto: update
  properties:
    hibernate:
      show_sql: false
      format_sql: false
#  properties:
#    jadira:
#      usertype:
#        autoRegisterUserTypes: true

spring.jmx:
  enabled: false

spring.jackson:
  serialization:
    WRITE_DATES_AS_TIMESTAMPS: false
    INDENT_OUTPUT: true
  default-property-inclusion: non_null

springdoc:
  swagger-ui:
    display-operation-id: true
    display-request-duration: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true

logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd'T'HH:mm:ss.SSSXXX}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m %boldMagenta(%X){faint} %n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
