server:
  port: 5000

spring.datasource:
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:exchange_rates;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
  username: sa
  password:

spring.h2.console:
  enabled: false
  path: /h2

spring.jpa:
  hibernate:
    ddlAuto: update
    naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
    show-sql: true
    format_sql: true
  show-sql: false
#  properties:
#    jadira:
#      usertype:
#        autoRegisterUserTypes: true

spring.jmx:
  enabled: false

spring.jackson.serialization:
  WRITE_DATES_AS_TIMESTAMPS: false
  INDENT_OUTPUT: true
