CREATE TABLE currency (
    code               VARCHAR(3)     NOT NULL,
    display_name       VARCHAR(255),
    start_date         DATE,
    end_date           DATE,
    created_date       TIMESTAMP      NOT NULL,
    last_modified_date TIMESTAMP      NOT NULL,
    PRIMARY KEY (code)
);

CREATE TABLE exchange_rate (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    currency_code      VARCHAR(3)     NOT NULL,
    exchange_date      DATE           NOT NULL,
    exchange_rate      DECIMAL(19, 6) NOT NULL,
    created_date       TIMESTAMP      NOT NULL,
    last_modified_date TIMESTAMP      NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT UK_ExchangeRate_currency_id_exchange_date
        UNIQUE (currency_code, exchange_date),
    CONSTRAINT FK_ExchangeRate_currency
        FOREIGN KEY (currency_code) REFERENCES currency (code)
);
